[project]
src = "src"
out = "out"
dot_env = ".env"
dependencies = ["snekmate"]

[networks.anvil]
url = "http://127.0.0.1:8545"
prompt_live = false
# save_to_db = false
chain_id = 31337
default_account_name = "anvil0"


# You can view all configuration options at https://cyfrin.github.io/moccasin/all_moccasin_toml_parameters.html
